### ISSUE TITLE
feedback form

### ISSUE THREAD

**Issue by HerziPinki** [reiterbene/WikiDaheim#138]
I've heard that the feedback form is not working anymore. True?

The proposal is to replace it by a simple email to wikidaheim@wikimedia.at
Of course this needs to be spam-bot protected.

**Comment by reiterbene** [comment]
i just tested it and it seems to be working - at least it submits y message to the backend API

**Comment by HerziPinki** [comment]
the last message is ''Hier handelt es sich um ein AquÃ¤dukt der II. Wiener Wasserleitung und nicht um einen Kanal!'' and at least 3 years old. I sent 2 test messages, they are not in the protocol.
- not very useful
- not even a timestamp

Proposal (instead of fixing the problems): 
remove the feedback tab
instead add the email 'wikidaheim@wikimedia.at' to the bottom of the main menu
instead of facebook (?)

I can do that.
