### ISSUE TITLE
certain urls blank the page

### ISSUE THREAD

**Issue by HerziPinki** [reiterbene/WikiDaheim#172]
e.g. https://wikidaheim.at/Q1
(where Q1 is a WikiData id, that does not denote an Austrian municipality) will blank the page.

While https://wikidaheim.at/q1 or https://wikidaheim.at/xxxx will not. Instead these invalid urls will redirect to the start page.

Urls like https://wikidaheim.at/Qnnnn where nnnn isn't a known id of an existing municipality, should behave similar. But when the Qid is a valid municipality, it should load that municipality.

**Comment by HerziPinki** [comment]
bene, can you please have a look on this issue

**Comment by HerziPinki** [comment]
well, https://wikidaheim.at/Q87637599 (invalid Qid) still blanks the page. But https://wikidaheim.at returns to the initial state of the app, which is an improvement.

Opening https://wikidaheim.at/Q876375 shows the municipality, a consecutive https://wikidaheim.at/Q87637599 shows the old municipality for a moment (until server returns data?) and then blanks the page.

Can you please add an error message in case the Q-id / municipality is not found? You can use the input field for the municipality to show something like 'nicht gefunden' / 'not found'. 

It is crucial to get the initial page of the app and the home-button (Icon left upper corner).

**Comment by reiterbene** [comment]
The code is not yet live but only in the specific branch. If requested I can push it to the live environment tomorrow for testing.

**Comment by HerziPinki** [comment]
https://github.com/Wikimedia-Austria/WikiDaheim/pull/197 fixes the problem
