### ISSUE TITLE
WikiDaheim does not work with IE 11

### ISSUE THREAD

**Issue by pkopetzky** [reiterbene/WikiDaheim#19]
Console spits out this error: Minified React error #39; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=39&args[]=%20This%20may%20be%20caused%20by%20unintentionally%20loading%20two%20independent%20copies%20of%20React. for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

The non-minimized version issues a different error message, so it's a bit unclear what exactly is going on with IE.

**Comment by reiterbene** [comment]
fixed with #22
