### ISSUE TITLE
When jumping between views user is not pushed to top

### ISSUE THREAD

**Issue by 5k9m** [reiterbene/WikiDaheim#5]
Hey,
when I jump between the views after scrolling, the upcoming view is still in the same position - leading to the case that the user starts reading from the middle: 

![scrolltop_issue](https://user-images.githubusercontent.com/13706131/29042078-c2d8eece-7bb5-11e7-863a-944db46c6a4f.gif)

**Comment by reiterbene** [comment]
will be fixed with #12

**Comment by reiterbene** [comment]
closed, as #12 is merged
